server:
  port: 8082

spring:
  application:
    name: commerce
  cloud:
    stream:
      bindings:
        purchaseEvent:
          destination: purchase-topic
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: 'http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans'
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info

productapi:
  url: ${PRODUCT_API_URL:http://localhost:8888/}
