spring:
  application:
    name: monomart

management:
  tracing:
    enabled: true
    sampling.probability: 1.0
  zipkin.tracing.endpoint: 'http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans'
  endpoints:
    web:
      exposure:
        include: health,prometheus,metrics,info