server:
  port: 8081

spring:
  application:
    name: inventory
  cloud:
    stream:
      function:
        definition: purchaseEvent
      bindings:
        purchaseEvent-in-0:
          destination: purchase-topic
  rabbitmq:
    host: ${RABBIT_HOST:localhost}

management:
  tracing:
    enabled: true
    sampling.probability: 1.0