server:
  port: 8081

spring:
  application:
    name: inventory
  cloud:
    stream:
      function:
        definition: purchaseEvent
      bindings:
        purchaseEvent-in-0:
          destination: purchase-topic

productapi:
  url: ${PRODUCT_API_URL:http://localhost:8888/}