server.port: 8083

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: 'https://gitlab.vulcan.mil/army-software-factory/product-office/sdu-3/3-3/tesseract/experimental/tempgit'
          skipSslValidation: true
          username: 'Job-Token'
          password: '${CI_JOB_TOKEN}'